### PR TITLE
Add a branch label to workflow metrics

### PR DESCRIPTION
**Pull request by rguliyev**
This will add  a `branch` label to the workflow metrics `(workflow_*)` as requested in https://github.com/cpanato/github_actions_exporter/issues/154

### CODE REVIEW

**Comment by cpanato** [comment]
thanks for the PR, can you please sign the DCO and also need to rebase

**Comment by rguliyev** [comment]
done

**Comment by peterhalasz** [comment]
@rguliyev I think there's lots of value in this feature, are you sure you don't want to merge it?

**Comment by cpanato** [comment]
I think so, do you want to reopen this pr?

**Comment by cpanato** [comment]
@rguliyev thanks, a rebase will require

**Comment by rguliyev** [comment]
> @rguliyev thanks, a rebase will require

done

**Review by cpanato — APPROVED** [review]
thanks!

**Pull request merged**
