### PR TITLE
Adds workflow_job_seconds metric

### PR DESCRIPTION
**Pull request by janakerman**
Fixes https://github.com/cpanato/github_actions_exporter/issues/4

This PR brings a number of improvements, mainly to support testing:
* Adds `workflow_job_duration_seconds`
  * This metric is made possible by the `workflow_job` events
  * This metric tracks the dimension `state` which has two possible values:
    * `queued` - the amount of time the job spent queued waiting for a runner
    * `in_progress` - the amount of time the job spent in progress whilst completing all steps
  * `WorkflowJobObserver` interface created to allow for testing of observations without interacting with Prometheus lib.
* Adds integration tests
  * Extracts application logic out of main and into `Server` struct to allow for start + stop of server with different configurations.

The PR brings more changes than actually needed to add the new metric (i.e extracting behaviour to a `Server` struct in an additional package. I can try to unpick these changes into a smaller but I think the other changes are worth considering.

The individual commits should largely be complete and documented.

---

Still TODO as part of this PR:
- [x] Run locally and test with real Github events
  - Tested with two workflows and manually verified /metrics content
- [x] ~Remove check_run event handling~ - this doesn't make sense - we'd need to add the workflow event handler for that one and I'd rather do that as a separate PR.
  * ~Record `workflow_execution_time_seconds` using the `workflow_job` `completed` event~ 

Still TODO hopefully out of scope for this PR:
* Backfill tests for other observations
* Improve integration tests to check for additional metrics
* Fix observation inconsistencies - some observations are against the global collector, and the new observations are against an interface.
* Track additional metrics made possible by this new event type.

### CODE REVIEW

**Comment by cpanato** [comment]
looks great, i will run locally, let me know when you are ready and then set the PR out from draft!
thanks so much for this

**Comment by janakerman** [comment]
Awesome, thanks!

The build failed - the lint stage passes locally for me. The error suggests something about updating the tool so I've bumped the golangci-lint version to latest:

```
level=error msg="Running error: buildir: failed to load package goarch: could not load export data: cannot import \"internal/goarch\" (unknown iexport format version 2), export data is newer version - update tool"

```

**Comment by janakerman** [comment]
I tested the exporter locally and ran a couple of workflows. I spotted a few issues which I've fixed up and added tests for.

**Review by cpanato — APPROVED** [review]
I will merge and if we found any issues we can fix that in a follow up
I need to refactor the release pipeline and decouple some things which I will do soon

thanks so much for this change it is super cool!

**Pull request merged**
