### PR TITLE
Adds docker-compose.yml for local example

### PR DESCRIPTION
**Pull request by janakerman**
I've been using this for local experimentation. I figured it might be useful for local testing.

Signed-off-by: Jan Akerman <janakerman@users.noreply.github.com>

### CODE REVIEW

**Comment by janakerman** [comment]
@cpanato - what do you think? Worth merging?

**Comment by cpanato** [comment]
this will break the release because we are using goreleaser to build the image based on the binary that we built before

**Comment by cpanato** [comment]
i recommend to add a `dockerfile.dev` to use in this case

**Comment by janakerman** [comment]
@cpanato - sorry for the delay in getting back to you. Adding a Dockerfile.dev seems like a good idea to me.

**Review by cpanato — APPROVED** [review]
thanks!

**Pull request merged**
